import factory
from .user_profile_factory import UserProfileFactory
from food_intake.nutrition_stats import NutritionStats

class NutritionStatsFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = NutritionStats

    profile = factory.SubFactory(UserProfileFactory)
    last_week_calories = factory.Faker('pyfloat', positive=True)
    last_week_fat = factory.Faker('pyfloat', positive=True)
    last_week_saturated_fat = factory.Faker('pyfloat', positive=True)
    last_week_carbohydrates = factory.Faker('pyfloat', positive=True)
    last_week_sugar = factory.Faker('pyfloat', positive=True)
    last_week_protein = factory.Faker('pyfloat', positive=True)
    last_week_cholesterol = factory.Faker('pyfloat', positive=True)
    last_week_sodium = factory.Faker('pyfloat', positive=True)
    last_week_fiber = factory.Faker('pyfloat', positive=True)
    last_week_vitamin_c = factory.Faker('pyfloat', positive=True)
    last_week_manganese = factory.Faker('pyfloat', positive=True)
    last_week_folate = factory.Faker('pyfloat', positive=True)
    last_week_potassium = factory.Faker('pyfloat', positive=True)
    last_week_magnesium = factory.Faker('pyfloat', positive=True)
    last_week_vitamin_a = factory.Faker('pyfloat', positive=True)
    last_week_vitamin_b6 = factory.Faker('pyfloat', positive=True)
    last_week_vitamin_b12 = factory.Faker('pyfloat', positive=True)
    last_week_vitamin_d = factory.Faker('pyfloat', positive=True)
    last_week_calcium = factory.Faker('pyfloat', positive=True)
    last_week_iron = factory.Faker('pyfloat', positive=True)
    last_week_zinc = factory.Faker('pyfloat', positive=True)
    last_week_vitamin_e = factory.Faker('pyfloat', positive=True)
    last_week_vitamin_k = factory.Faker('pyfloat', positive=True)
    last_week_omega_3 = factory.Faker('pyfloat', positive=True)
    last_week_omega_6 = factory.Faker('pyfloat', positive=True)

    last_30_days_calories = factory.Faker('pyfloat', positive=True)
    last_30_days_fat = factory.Faker('pyfloat', positive=True)
    last_30_days_saturated_fat = factory.Faker('pyfloat', positive=True)
    last_30_days_carbohydrates = factory.Faker('pyfloat', positive=True)
    last_30_days_sugar = factory.Faker('pyfloat', positive=True)
    last_30_days_protein = factory.Faker('pyfloat', positive=True)
    last_30_days_cholesterol = factory.Faker('pyfloat', positive=True)
    last_30_days_sodium = factory.Faker('pyfloat', positive=True)
    last_30_days_fiber = factory.Faker('pyfloat', positive=True)
    last_30_days_vitamin_c = factory.Faker('pyfloat', positive=True)
    last_30_days_manganese = factory.Faker('pyfloat', positive=True)
    last_30_days_folate = factory.Faker('pyfloat', positive=True)
    last_30_days_potassium = factory.Faker('pyfloat', positive=True)
    last_30_days_magnesium = factory.Faker('pyfloat', positive=True)
    last_30_days_vitamin_a = factory.Faker('pyfloat', positive=True)
    last_30_days_vitamin_b6 = factory.Faker('pyfloat', positive=True)
    last_30_days_vitamin_b12 = factory.Faker('pyfloat', positive=True)
    last_30_days_vitamin_d = factory.Faker('pyfloat', positive=True)
    last_30_days_calcium = factory.Faker('pyfloat', positive=True)
    last_30_days_iron = factory.Faker('pyfloat', positive=True)
    last_30_days_zinc = factory.Faker('pyfloat', positive=True)
    last_30_days_vitamin_e = factory.Faker('pyfloat', positive=True)
    last_30_days_vitamin_k = factory.Faker('pyfloat', positive=True)
    last_30_days_omega_3 = factory.Faker('pyfloat', positive=True)
    last_30_days_omega_6 = factory.Faker('pyfloat', positive=True)