# Generated by Django 5.0.2 on 2024-04-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='caloricBreakdown',
            new_name='weight_per_serving',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='weightPerServing',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='percent_carbs',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition',
            name='percent_fat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition',
            name='percent_protein',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
