# Generated by Django 4.2.1 on 2024-04-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_rename_caloricbreakdown_nutrition_weight_per_serving_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="spoonacular_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="spoonacular_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
