# Generated by Django 5.0.3 on 2024-04-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0004_recipe_servings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutrition",
            name="flavonoids",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrition",
            name="nutrients",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrition",
            name="percent_carbs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrition",
            name="percent_fat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrition",
            name="percent_protein",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrition",
            name="properties",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrition",
            name="weight_per_serving",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
