# Generated by Django 5.0.2 on 2024-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', 'manage_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activityLevel',
            field=models.CharField(choices=[('Sedentary', 'Sedentary'), ('slightly_active', 'Slightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active'), ('super_active', 'Super Active')], default='Sedentary', max_length=20),
        ),
    ]
