# Generated by Django 5.0.2 on 2024-04-02 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecipe',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='userrecipe',
            name='recipe_id',
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
            preserve_default=False,
        ),
    ]
