# Generated by Django 5.0.2 on 2024-03-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activityLevel',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
