# Generated by Django 5.0.2 on 2024-04-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_rename_caloricbreakdown_nutrition_weight_per_serving_and_more"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="saved_recipes",
            field=models.ManyToManyField(
                null=True, related_name="saved_by_profiles", to="foods.recipe"
            ),
        ),
    ]
