# Generated by Django 5.0.2 on 2024-04-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_rename_caloricbreakdown_nutrition_weight_per_serving_and_more"),
        ("profiles", "0002_alter_userprofile_saved_recipes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="saved_recipes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="saved_by_profiles",
                to="foods.recipe",
            ),
        ),
    ]
