# Generated by Django 5.0.2 on 2024-04-03 12:45

import profiles.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userdaily_total_carbohydrates_consumed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdaily',
            name='total_calories_consumed',
            field=models.FloatField(default=0.0, validators=[profiles.utils.validators.validate_positive_float]),
        ),
        migrations.AlterField(
            model_name='userdaily',
            name='total_carbohydrates_consumed',
            field=models.FloatField(default=0.0, validators=[profiles.utils.validators.validate_positive_float]),
        ),
        migrations.AlterField(
            model_name='userdaily',
            name='total_fat_consumed',
            field=models.FloatField(default=0.0, validators=[profiles.utils.validators.validate_positive_float]),
        ),
        migrations.AlterField(
            model_name='userdaily',
            name='total_protein_consumed',
            field=models.FloatField(default=0.0, validators=[profiles.utils.validators.validate_positive_float]),
        ),
    ]
