# Generated by Django 5.0.2 on 2024-03-21 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=85, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
