# Generated by Django 5.0.2 on 2024-03-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedrecipe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='savedrecipe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrecipe',
            name='user',
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='profile_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='recipe_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='profile_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='recipe_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
