# Generated by Django 5.0.3 on 2024-04-28 18:00

import django.core.validators
import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_userprofile_saved_recipes"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFitnessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("Lose", "Lose Weight"),
                            ("Maintain", "Maintain Weight"),
                            ("Gain", "Gain Weight"),
                        ],
                        default="Maintain",
                        max_length=10,
                    ),
                ),
                (
                    "daily_calorie_intake_goal",
                    models.PositiveIntegerField(
                        default=2000,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "daily_protein_goal",
                    models.FloatField(
                        default=50.0,
                        validators=[utils.validators.validate_positive_float],
                    ),
                ),
                (
                    "daily_fat_goal",
                    models.FloatField(
                        default=70.0,
                        validators=[utils.validators.validate_positive_float],
                    ),
                ),
                (
                    "daily_carbohydrate_goal",
                    models.FloatField(
                        default=250.0,
                        validators=[utils.validators.validate_positive_float],
                    ),
                ),
                (
                    "activity_level",
                    models.PositiveIntegerField(
                        default=1, validators=[utils.validators.validate_activity_level]
                    ),
                ),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fitness_profile",
                        to="profiles.userprofile",
                    ),
                ),
            ],
        ),
    ]
