# Generated by Django 5.0.2 on 2024-04-05 08:56

import django.core.validators
import profiles.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userdaily_total_calories_consumed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activityLevel',
            field=models.PositiveIntegerField(default=1, validators=[profiles.utils.validators.validate_activity_level]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(validators=[profiles.utils.validators.validate_is_date_before_today]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(default=170, validators=[profiles.utils.validators.validate_positive_float]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(default=80, validators=[profiles.utils.validators.validate_positive_float]),
        ),
    ]
