# Generated by Django 5.0.3 on 2024-04-29 12:53

import django.core.validators
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_userfitnessprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfitnessprofile",
            name="daily_calorie_intake_goal",
            field=models.PositiveIntegerField(
                default=2000,
                validators=[
                    django.core.validators.MinValueValidator(1200),
                    django.core.validators.MaxValueValidator(4500),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userfitnessprofile",
            name="daily_carbohydrate_goal",
            field=models.FloatField(
                default=250.0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                    utils.validators.validate_positive_float,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userfitnessprofile",
            name="daily_fat_goal",
            field=models.FloatField(
                default=70.0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(500),
                    utils.validators.validate_positive_float,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userfitnessprofile",
            name="daily_protein_goal",
            field=models.FloatField(
                default=50.0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(500),
                    utils.validators.validate_positive_float,
                ],
            ),
        ),
    ]
