# Generated by Django 5.0.3 on 2024-04-29 15:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0006_alter_userfitnessprofile_daily_calorie_intake_goal_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Allergy",
            new_name="Allergies",
        ),
    ]
