# Generated by Django 5.0.2 on 2024-04-12 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodintakedetail',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='foodintakedetail',
            name='food_id',
            field=models.PositiveIntegerField(),
        ),
    ]
