# Generated by Django 5.0.3 on 2024-05-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_intake", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodintakedetail",
            name="recipe",
        ),
    ]
