# Generated by Django 5.0.2 on 2024-04-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_intake', '0002_alter_foodintakedetail_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodintake',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20, verbose_name='Meal Type'),
        ),
    ]
