# Generated by Django 5.0.3 on 2024-05-25 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_intake", "0003_foodintakedetail_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodintakedetail",
            name="food_intake",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="food_intake.foodintake"
            ),
        ),
    ]
