# Generated by Django 5.0.2 on 2024-04-12 08:41

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_intake', '0004_alter_foodintake_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodintake',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20, validators=[utils.validators.validate_meal_type]),
        ),
    ]
