# Generated by Django 5.0.3 on 2024-05-31 17:07

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_intake", "0004_alter_foodintakedetail_food_intake"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdaily",
            name="id",
        ),
        migrations.AlterField(
            model_name="userdaily",
            name="date",
            field=models.DateField(
                primary_key=True,
                serialize=False,
                validators=[utils.validators.validate_is_date_before_today],
            ),
        ),
    ]
