# Generated by Django 5.0.2 on 2024-04-20 18:06

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_intake", "0006_remove_foodintake_user_daily_foodintake_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodintake",
            name="date",
            field=models.DateField(validators=[utils.validators.validate_meal_type]),
        ),
    ]
