# Generated by Django 5.0.2 on 2024-04-20 18:21

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_intake", "0008_alter_foodintake_date"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodintake",
            name="date",
            field=models.DateField(
                verbose_name=utils.validators.validate_is_date_before_today
            ),
        ),
        migrations.AlterField(
            model_name="foodintake",
            name="profile",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="foodintake",
            table="foodintake_foodintake",
        ),
    ]
