export const filters = [
    { name: "query", label: "Recipe Search Query", type: "text" },
    { name: "cuisine", label: "Cuisine", type: "text" },
    { name: "excludeCuisine", label: "Exclude Cuisine", type: "text" },
    { name: "diet", label: "Diet", type: "text" },
    { name: "intolerances", label: "Intolerances", type: "text" },
    { name: "equipment", label: "Equipment", type: "text" },
    { name: "includeIngredients", label: "Include Ingredients", type: "text" },
    { name: "excludeIngredients", label: "Exclude Ingredients", type: "text" },
    { name: "type", label: "Recipe Type", type: "text" },
    { name: "instructionsRequired", label: "Instructions Required", type: "boolean" },
    { name: "fillIngredients", label: "Fill Ingredients", type: "boolean" },
    { name: "addRecipeInformation", label: "Add Recipe Information", type: "boolean" },
    { name: "addRecipeNutrition", label: "Add Recipe Nutrition", type: "boolean" },
    { name: "author", label: "Author", type: "text" },
    { name: "tags", label: "Tags", type: "text" },
    { name: "recipeBoxId", label: "Recipe Box ID", type: "number" },
    { name: "titleMatch", label: "Title Match", type: "text" },
    { name: "maxReadyTime", label: "Max Ready Time (minutes)", type: "number" },
    { name: "ignorePantry", label: "Ignore Pantry", type: "boolean" },
    { name: "sort", label: "Sort By", type: "text" },
    { name: "sortDirection", label: "Sort Direction", type: "text" },
    { name: "minCarbs", label: "Minimum Carbs (g)", type: "number" },
    { name: "maxCarbs", label: "Maximum Carbs (g)", type: "number" },
    { name: "minProtein", label: "Minimum Protein (g)", type: "number" },
    { name: "maxProtein", label: "Maximum Protein (g)", type: "number" },
    { name: "minCalories", label: "Minimum Calories", type: "number" },
    { name: "maxCalories", label: "Maximum Calories", type: "number" },
    { name: "minFat", label: "Minimum Fat (g)", type: "number" },
    { name: "maxFat", label: "Maximum Fat (g)", type: "number" },
    { name: "minAlcohol", label: "Minimum Alcohol (g)", type: "number" },
    { name: "maxAlcohol", label: "Maximum Alcohol (g)", type: "number" },
    { name: "minCaffeine", label: "Minimum Caffeine (mg)", type: "number" },
    { name: "maxCaffeine", label: "Maximum Caffeine (mg)", type: "number" },
    { name: "minCopper", label: "Minimum Copper (mg)", type: "number" },
    { name: "maxCopper", label: "Maximum Copper (mg)", type: "number" },
    { name: "minCalcium", label: "Minimum Calcium (mg)", type: "number" },
    { name: "maxCalcium", label: "Maximum Calcium (mg)", type: "number" },
    { name: "minCholine", label: "Minimum Choline (mg)", type: "number" },
    { name: "maxCholine", label: "Maximum Choline (mg)", type: "number" },
    { name: "minCholesterol", label: "Minimum Cholesterol (mg)", type: "number" },
    { name: "maxCholesterol", label: "Maximum Cholesterol (mg)", type: "number" },
    { name: "minFluoride", label: "Minimum Fluoride (mg)", type: "number" },
    { name: "maxFluoride", label: "Maximum Fluoride (mg)", type: "number" },
    { name: "minSaturatedFat", label: "Minimum Saturated Fat (g)", type: "number" },
    { name: "maxSaturatedFat", label: "Maximum Saturated Fat (g)", type: "number" },
    { name: "minVitaminA", label: "Minimum Vitamin A (IU)", type: "number" },
    { name: "maxVitaminA", label: "Maximum Vitamin A (IU)", type: "number" },
    { name: "minVitaminC", label: "Minimum Vitamin C (mg)", type: "number" },
    { name: "maxVitaminC", label: "Maximum Vitamin C (mg)", type: "number" },
    { name: "minVitaminD", label: "Minimum Vitamin D (µg)", type: "number" },
    { name: "maxVitaminD", label: "Maximum Vitamin D (µg)", type: "number" },
    { name: "minVitaminE", label: "Minimum Vitamin E (mg)", type: "number" },
    { name: "maxVitaminE", label: "Maximum Vitamin E (mg)", type: "number" },
    { name: "minVitaminK", label: "Minimum Vitamin K (µg)", type: "number" },
    { name: "maxVitaminK", label: "Maximum Vitamin K (µg)", type: "number" },
    { name: "minVitaminB1", label: "Minimum Vitamin B1 (mg)", type: "number" },
    { name: "maxVitaminB1", label: "Maximum Vitamin B1 (mg)", type: "number" },
    { name: "minVitaminB2", label: "Minimum Vitamin B2 (mg)", type: "number" },
    { name: "maxVitaminB2", label: "Maximum Vitamin B2 (mg)", type: "number" },
    { name: "minVitaminB5", label: "Minimum Vitamin B5 (mg)", type: "number" },
    { name: "maxVitaminB5", label: "Maximum Vitamin B5 (mg)", type: "number" },
    { name: "minVitaminB3", label: "Minimum Vitamin B3 (mg)", type: "number" },
    { name: "maxVitaminB3", label: "Maximum Vitamin B3 (mg)", type: "number" },
    { name: "minVitaminB6", label: "Minimum Vitamin B6 (mg)", type: "number" },
    { name: "maxVitaminB6", label: "Maximum Vitamin B6 (mg)", type: "number" },
    { name: "minVitaminB12", label: "Minimum Vitamin B12 (µg)", type: "number" },
    { name: "maxVitaminB12", label: "Maximum Vitamin B12 (µg)", type: "number" },
    { name: "minFiber", label: "Minimum Fiber (g)", type: "number" },
    { name: "maxFiber", label: "Maximum Fiber (g)", type: "number" },
    { name: "minFolate", label: "Minimum Folate (µg)", type: "number" },
    { name: "maxFolate", label: "Maximum Folate (µg)", type: "number" },
    { name: "minFolicAcid", label: "Minimum Folic Acid (µg)", type: "number" },
    { name: "maxFolicAcid", label: "Maximum Folic Acid (µg)", type: "number" },
    { name: "minIodine", label: "Minimum Iodine (µg)", type: "number" },
    { name: "maxIodine", label: "Maximum Iodine (µg)", type: "number" },
    { name: "minIron", label: "Minimum Iron (mg)", type: "number" },
    { name: "maxIron", label: "Maximum Iron (mg)", type: "number" },
    { name: "minMagnesium", label: "Minimum Magnesium (mg)", type: "number" },
    { name: "maxMagnesium", label: "Maximum Magnesium (mg)", type: "number" },
    { name: "minManganese", label: "Minimum Manganese (mg)", type: "number" },
    { name: "maxManganese", label: "Maximum Manganese (mg)", type: "number" },
    { name: "minPhosphorus", label: "Minimum Phosphorus (mg)", type: "number" },
    { name: "maxPhosphorus", label: "Maximum Phosphorus (mg)", type: "number" },
    { name: "minPotassium", label: "Minimum Potassium (mg)", type: "number" },
    { name: "maxPotassium", label: "Maximum Potassium (mg)", type: "number" },
    { name: "minSelenium", label: "Minimum Selenium (µg)", type: "number" },
    { name: "maxSelenium", label: "Maximum Selenium (µg)", type: "number" },
    { name: "minSodium", label: "Minimum Sodium (mg)", type: "number" },
    { name: "maxSodium", label: "Maximum Sodium (mg)", type: "number" },
    { name: "minSugar", label: "Minimum Sugar (g)", type: "number" },
    { name: "maxSugar", label: "Maximum Sugar (g)", type: "number" },
    { name: "minZinc", label: "Minimum Zinc (mg)", type: "number" },
    { name: "maxZinc", label: "Maximum Zinc (mg)", type: "number" },
    { name: "offset", label: "Offset", type: "number" },
    { name: "number", label: "Number of Results", type: "number" },
    { name: "limitLicense", label: "Limit License", type: "boolean" }
  ];
  